"""
Evidence pipeline for the AI research analyst.

collect → deduplicate → score source reliability → rank → cite.

Every memo claim must trace to an EvidenceItem with a stable ID ([E1]…[En]).
The LLM never sees raw vendors — only this ranked, attributed evidence table,
which is also what builds the memo's Source Attribution section (so
attribution is constructed from data, never generated by the model).
"""

from __future__ import annotations

import logging
import math
import re
from datetime import datetime, timezone
from typing import Optional
from urllib.parse import urlparse

from pydantic import BaseModel, Field

from src import providers

logger = logging.getLogger(__name__)

# ── Source reliability tiers ──────────────────────────────────────────────────
# Editorial standards, not popularity: wire services and papers of record
# above network financial media, above aggregators/unknown domains, above
# user-generated content. Used multiplicatively in ranking and reported
# per-item so the model (and the reader) can weigh claims.

RELIABILITY_TIERS: dict[float, tuple[str, ...]] = {
    1.00: ("reuters.com", "bloomberg.com", "wsj.com", "ft.com", "apnews.com"),
    0.85: ("cnbc.com", "marketwatch.com", "barrons.com", "economist.com",
           "fortune.com", "businessinsider.com", "finance.yahoo.com"),
    0.65: ("seekingalpha.com", "fool.com", "investing.com", "benzinga.com",
           "thestreet.com", "barchart.com", "investopedia.com"),
}
DEFAULT_RELIABILITY = 0.50   # unknown domains
UGC_RELIABILITY = 0.30       # user-generated content
UGC_DOMAINS = ("reddit.com", "twitter.com", "x.com", "stocktwits.com", "medium.com")

RECENCY_HALF_LIFE_HOURS = 48.0   # news information decays fast
MAX_EVIDENCE = 12


class EvidenceItem(BaseModel):
    id: str                      # "E1"… — the citation handle
    title: str
    snippet: str = ""
    url: str = ""
    source: str = ""
    domain: str = ""
    published_at: str = ""
    reliability: float = Field(DEFAULT_RELIABILITY, ge=0, le=1)
    recency: float = Field(0.5, ge=0, le=1)
    relevance: float = Field(0.5, ge=0, le=1)
    rank_score: float = 0.0
    kind: str = "news"           # "news" | "search"


def domain_of(url: str) -> str:
    try:
        host = urlparse(url).netloc.lower()
        return host[4:] if host.startswith("www.") else host
    except ValueError:
        return ""


def reliability_of(url: str, source_name: str = "") -> float:
    domain = domain_of(url)
    haystack = f"{domain} {source_name.lower()}"
    for score, domains in RELIABILITY_TIERS.items():
        if any(d in haystack for d in domains):
            return score
    if any(d in haystack for d in UGC_DOMAINS):
        return UGC_RELIABILITY
    return DEFAULT_RELIABILITY


def recency_of(published_at: str, now: Optional[datetime] = None) -> float:
    """Exponential decay with a 48h half-life; unknown dates get 0.5."""
    if not published_at:
        return 0.5
    timestamp = _parse_when(published_at)
    if timestamp is None:
        return 0.5
    age_hours = max(0.0, ((now or datetime.now(timezone.utc)) - timestamp).total_seconds() / 3600)
    return float(0.5 ** (age_hours / RECENCY_HALF_LIFE_HOURS))


def _parse_when(raw: str) -> Optional[datetime]:
    candidate = raw.strip()
    for parser in (
        lambda v: datetime.fromisoformat(v.replace("Z", "+00:00")),
        lambda v: datetime.strptime(v, "%a, %d %b %Y %H:%M:%S %z"),
        lambda v: datetime.strptime(v, "%a, %d %b %Y %H:%M:%S %Z").replace(tzinfo=timezone.utc),
    ):
        try:
            parsed = parser(candidate)
            return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)
        except (ValueError, TypeError):
            continue
    return None


def relevance_of(title: str, snippet: str, ticker: str, company_name: str) -> float:
    """Crude but transparent: direct ticker/company mention beats topical match."""
    haystack = f"{title} {snippet}".lower()
    score = 0.4  # arrived via a ticker-scoped query, so baseline topical
    if ticker.lower() in re.findall(r"[a-z.]+", haystack):
        score += 0.3
    if company_name:
        loose = company_name.lower().split()[0]
        if len(loose) >= 3 and loose in haystack:
            score += 0.3
    return min(1.0, score)


def _dedupe_key(title: str, url: str) -> str:
    normalized = re.sub(r"[^a-z0-9 ]", "", title.lower())
    normalized = re.sub(r"\s+", " ", normalized).strip()[:80]
    return normalized or url


def collect_evidence(
    ticker: str,
    company_name: str = "",
    max_items: int = MAX_EVIDENCE,
    now: Optional[datetime] = None,
) -> list[EvidenceItem]:
    """
    Gather from NewsProvider + SearchProvider, dedupe, score, rank,
    and assign citation IDs. Never raises; empty list means no evidence.
    """
    raw: list[EvidenceItem] = []

    try:
        news_result = providers.news.get_news(ticker, company_name, limit=max_items)
        if news_result.ok and news_result.data:
            for headline in news_result.data:
                raw.append(EvidenceItem(
                    id="", title=headline.title, snippet=headline.summary,
                    url=headline.url, source=headline.source,
                    domain=domain_of(headline.url),
                    published_at=headline.published_at, kind="news",
                ))
    except Exception:  # noqa: BLE001 — evidence is best-effort by design
        logger.exception("news evidence failed for %s", ticker)

    try:
        query = f"{company_name or ticker} stock analysis outlook"
        search_result = providers.search.search(query, limit=6)
        if search_result.ok and search_result.data:
            for row in search_result.data:
                raw.append(EvidenceItem(
                    id="", title=row.title, snippet=row.snippet, url=row.url,
                    source=domain_of(row.url) or "web",
                    domain=domain_of(row.url),
                    published_at=row.published_at, kind="search",
                ))
    except Exception:  # noqa: BLE001
        logger.exception("search evidence failed for %s", ticker)

    # Deduplicate (normalized title, then exact URL)
    seen_titles: set[str] = set()
    seen_urls: set[str] = set()
    unique: list[EvidenceItem] = []
    for item in raw:
        title_key = _dedupe_key(item.title, item.url)
        url_key = item.url.split("?")[0] if item.url else ""
        if title_key in seen_titles or (url_key and url_key in seen_urls):
            continue
        seen_titles.add(title_key)
        if url_key:
            seen_urls.add(url_key)
        unique.append(item)

    # Score and rank
    for item in unique:
        item.reliability = reliability_of(item.url, item.source)
        item.recency = round(recency_of(item.published_at, now), 4)
        item.relevance = round(relevance_of(item.title, item.snippet, ticker, company_name), 4)
        item.rank_score = round(item.reliability * (0.5 + 0.5 * item.recency) * item.relevance, 4)

    ranked = sorted(unique, key=lambda item: item.rank_score, reverse=True)[:max_items]
    for index, item in enumerate(ranked, start=1):
        item.id = f"E{index}"
    return ranked


def citation_ids(evidence: list[EvidenceItem]) -> set[str]:
    return {item.id for item in evidence}


def extract_citations(text: str) -> set[str]:
    """All [E#] citations appearing in a memo string."""
    return set(re.findall(r"\[(E\d+)\]", text or ""))
