"""Render docs/quant/FEATURES.md from the registry.

Generated rather than written, because a hand-maintained feature table drifts
from the code the first time someone adds a feature and forgets — and a feature
document that is wrong about which features exist is worse than none, since it
is the artifact a reviewer checks the point-in-time claims against.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

from src.quant.features import (  # noqa: F401 - registration side effect
    earnings, estimates, fundamentals, macro, options, price,
)
from src.quant.features.registry import REGISTRY

HEADER = """# Feature Library

> Generated by `python -m scripts.quant.render_feature_docs`. Do not edit by hand —
> it is rendered from `src/quant/features/registry.py`, so it cannot disagree with
> the code that builds the panel.

Every feature declares a lookback, a direction hypothesis recorded **before**
testing, and its point-in-time status. A feature that is not registered cannot
enter an experiment.

## Reading the table

* **Lookback** — sessions of history the value depends on. The dataset builder
  refuses a symbol block shorter than the longest lookback.
* **Direction** — the sign of the *hypothesised* relationship, written down in
  advance so a factor that works with the opposite sign is visibly a surprise
  rather than retroactively "what we expected". `descriptive` claims none.
* **PIT** — whether the value is knowable on its own date. Everything here is
  point-in-time safe; sources that are not are refused upstream, in the catalog.

Features are consumed as **cross-sectional ranks** within the point-in-time
universe (suffix `_xs`), except macro features which are used raw. Ranking is
fitted per date, which is why it cannot leak across dates.

"""

GROUP_NOTES = {
    "fundamental": (
        "Two very different sources share this group and must not be read alike.\n\n"
        "`est_*` come from `eps_estimate` / `sales_estimate`, which are keyed by\n"
        "OBSERVATION date — they need no publication gate and carry no restatement\n"
        "risk. `fund_*` come from the statement tables, which are keyed by fiscal\n"
        "PERIOD END; they reach the panel only behind an `earnings_calendar`\n"
        "announcement join, and they carry **UNQUANTIFIED restatement risk** because\n"
        "the source holds one row per period with no vintage column.\n"
    ),
    "options": (
        "Derived from `volatility_history` and aggregated `option_chain`. Note what\n"
        "the schema does **not** contain: there is no open interest and no traded\n"
        "volume, so put/call volume imbalance, open-interest imbalance, dealer gamma\n"
        "exposure and unusual-activity measures are **not computable** from this\n"
        "source and are not implemented. Claiming them would require inventing them.\n"
    ),
}


def render() -> str:
    by_group: dict[str, list] = defaultdict(list)
    for name in REGISTRY.names(pit_only=False):
        definition = REGISTRY.get(name)
        by_group[definition.group.value].append(definition)

    lines = [HEADER]
    total = sum(len(v) for v in by_group.values())
    lines.append(f"**{total} registered features** across {len(by_group)} groups.\n")

    for group in sorted(by_group):
        definitions = sorted(by_group[group], key=lambda d: d.name)
        lines.append(f"\n## {group} ({len(definitions)})\n")
        if group in GROUP_NOTES:
            lines.append(GROUP_NOTES[group] + "\n")
        lines.append("| feature | description | formula | lookback | direction | PIT |")
        lines.append("|---|---|---|---|---|---|")
        for d in definitions:
            formula = d.formula.replace("|", "\\|")
            description = d.description.replace("|", "\\|")
            lines.append(
                f"| `{d.name}` | {description} | `{formula}` | {d.lookback_sessions} | "
                f"{d.direction.value} | {'yes' if d.point_in_time_safe else 'NO'} |"
            )

        cited = [d for d in definitions if d.citation]
        if cited:
            lines.append("\n<details><summary>Citations</summary>\n")
            for d in cited:
                lines.append(f"* `{d.name}` — {d.citation}")
            lines.append("\n</details>")

        risky = [d for d in definitions if any("UNQUANTIFIED" in n for n in d.notes)]
        if risky:
            lines.append(
                f"\n> **{len(risky)} features in this group carry UNQUANTIFIED "
                "restatement risk.** A later correction overwrites the original figure "
                "in the source, and the magnitude of that effect cannot be measured "
                "from the source alone.\n"
            )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="docs/quant/FEATURES.md", type=Path)
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(), encoding="utf-8")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
