"""Render docs/SEC_TAG_MAP_AUDIT.md from the measured v3 coverage manifest."""

from __future__ import annotations

import json
import sys
from pathlib import Path

from src.quant.pit import sec_facts as S

ROOT = Path(__file__).resolve().parents[2]


def main() -> int:
    payload = json.loads((ROOT / "data/manifests/sec_fact_coverage_v3.json").read_text())
    build, coverage = payload["build"], payload["coverage"]
    old = json.loads((ROOT / "data/manifests/sec_fact_coverage.json").read_text()) if (ROOT / "data/manifests/sec_fact_coverage.json").exists() else {}
    ex = build["exclusion_counts"]
    mapped, dimensional = ex["mapped_tag_rows"], ex["dimensional_excluded"]
    lines = [
        "# SEC tag map audit (`sec-core-facts-v3`)", "",
        "Generated by `python -m scripts.quant.render_sec_tag_audit` from `data/manifests/sec_fact_coverage_v3.json`; every",
        "number below is measured from the curated store, not recalled.", "",
        "## 1. Defects found in the v2 store (`sec-core-facts-v2`) and fixed in v3", "",
        "| # | Defect | Evidence | Fix |", "|---|---|---|---|",
        f"| 1 | Dimensional rows (segment, product, equity-component, related-party) were not excluded, so 'revenue' or 'equity' could be a segment or a component | of {mapped:,} rows carrying a mapped tag, **{dimensional:,} ({dimensional / mapped:.1%}) had a non-empty `segments` or `coreg`**; v2 recorded {old.get('conflict_count', 'n/a'):,} same-key conflicts and 1,129,457 'equity' rows for ~750 companies | only undimensioned rows enter the store; the excluded count is reported per build |",
        "| 2 | `unit` was never populated: the curation read a `unit` column that the source calls `uom`, so 100% of v2 `unit` values were null and USD, CAD and EUR facts could mix | measured on `facts-2020q1` v2: 118,268 of 118,268 null; raw 2020q1 `uom` includes CAD 2,508 and EUR 2,414 in the first 200,000 rows | each fact family names its unit (USD, shares, USD/shares); other units are rejected and counted |",
        "| 3 | v2 `as_of` sorted ascending on `tag_priority` and kept the *last* row, so when one filing carried several tags of a family the **fallback** tag beat the primary | code inspection of v2 `as_of`; the v3 regression test `test_as_of_prefers_the_primary_tag_within_the_same_filing` asserts the opposite | one canonical row per (fact key, filing) by highest priority, then the view picks the filing |",
        f"| 4 | v2 admitted a tag by its local name alone and had no `frame` (the bulk sets have none), so a company-extension tag sharing a us-gaap name, or an IFRS/other-unit row, could enter | v3 rejects {ex['wrong_taxonomy_or_unit']:,} rows for the wrong taxonomy family or unit; v2 `frame` was 100% null | a tag is accepted only from the family the map names (`us-gaap/…`, `dei/…`) in the unit it names |",
        "| 5 | Coverage was limited to the ~815 CIKs resolvable from today's ticker map, so delisted or renamed names had **no** fundamentals - missingness that correlates with future delisting | v2 candidate CIKs: 797 | v3 curates every periodic filer (all CIKs); identity is resolved afterwards, so a name resolved later gains its history |", "",
        "## 2. v3 build", "",
        f"* Archives: 58 (2011Q1–2025Q2), acceptance cutoff `{build['accepted_cutoff']}`, acceptance timezone `{build['acceptance_timezone']}` (EDGAR stamps US Eastern), market close `{build['market_close']}`.",
        f"* Rows considered in `num`: {ex['considered']:,}; with a mapped tag: {mapped:,}; dimensional excluded: {dimensional:,}; wrong taxonomy or unit: {ex['wrong_taxonomy_or_unit']:,}; context mismatch: {ex['context_mismatch_excluded']:,}; null value: {ex['null_value_excluded']:,}; **curated: {ex['curated']:,}**.",
        f"* Filings registry (all periodic filers): {build['registry_filings']:,} filings, {build['registry_ciks']:,} CIKs. Facts: {coverage['rows']:,} rows from {coverage['filings']:,} filings, {coverage['ciks']:,} CIKs, accepted {coverage['accepted_min']} → {coverage['accepted_max']}.",
        f"* Same filing, same tag, same period, **different values**: {coverage['duplicate_conflict_rows']} (source-level conflicts; never averaged). Filing-periods where two tags of one family disagree: {coverage['tag_disagreement_rows']:,} (reported; the higher-priority tag is used).", "",
        "## 3. Fact families", "",
        "| Fact | Primary tag | Fallbacks (priority order) | Unit | Context | Rows | CIKs | Fallback rate | Tag-disagreement rate |", "|---|---|---|---|---|---:|---:|---:|---:|",
    ]
    for fact, row in sorted(coverage["by_fact"].items()):
        lines.append(f"| `{fact}` | `{row['primary_tag']}` | {', '.join('`' + t + '`' for t in row['fallback_tags']) or '-'} | {row['unit']} | {row['context']} | "
                     f"{row['rows']:,} | {row['ciks']:,} | {row['fallback_rate']:.1%} | {row['tag_disagreement_rate']:.1%} |")
    notes = {f: s.note for f, s in S.FACTS.items() if s.note}
    lines += ["", "Economic caveats recorded with the map:", ""]
    lines += [f"* `{fact}`: {note}" for fact, note in sorted(notes.items())]
    lines += [
        "", "Rate definitions: *fallback rate* = share of (filing, period) facts whose chosen tag is not the primary tag (high for `revenue` because",
        "`RevenueFromContractWithCustomerExcludingAssessedTax` only exists after ASC 606, and near 100% for `shares_outstanding` because the",
        "`dei` cover-page count is not in the bulk `num` files after about 2014; see the security-master shares vintage for the API-sourced cover count).",
        "*Tag-disagreement rate* = share of (filing, period) facts where two tags of the family carry different values; where the tags are different",
        "economic quantities (`ProfitLoss` versus `NetIncomeLoss`, equity with versus without non-controlling interest) a disagreement is expected.", "",
        "## 4. Rules that are load-bearing", "",
        "1. **No random coalescing.** Priorities are fixed and versioned; a fallback is used only if a higher-priority tag is absent from that filing and period.",
        "2. **Vintages are never overwritten.** A 10-K/A or later filing is a new row; `FIRST_REPORTED` and `AS_OF(decision_time)` are views.",
        "3. **Availability is the acceptance time**, in US Eastern wall-clock time; accepted at or after 16:00 (or on a non-session day) means the next session.",
        "4. **Missing is missing.** Nothing is filled, defaulted or zero-substituted.",
        "5. `period_start` is derived from `qtrs` and labelled `derived_from_fsds_qtrs`; it never overwrites a source context.", "",
        "## 5. Known limits", "",
        "* The bulk data sets carry no XBRL `frame`, no `decimals`, and no per-context `dimensions` beyond the `segments` string; dimensional facts are excluded rather than modelled.",
        "* Multi-class companies report shares by class as dimensional rows; they are excluded from the bulk-derived balance-sheet share count and handled (summed and flagged) only in the API-sourced cover-page vintage.",
        "* `EntityCommonStockSharesOutstanding` is fetched per company from the SEC `companyconcept` API and dated by the FSDS acceptance time of its accession; an accession not present as a periodic filing in the registry is dropped.",
        "* The SEC states the `sic` and `name` in `sub` are as of the filing date; that is a statement by the source, not something re-verified here beyond the change-frequency check in `docs/RICH_PIT_PANEL_AUDIT.md`.", ""]
    (ROOT / "docs/SEC_TAG_MAP_AUDIT.md").write_text("\n".join(lines))
    print("wrote docs/SEC_TAG_MAP_AUDIT.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
