"""Render the PIT security-master status, the feature catalog and the rich-panel audit from measured manifests."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

from src.quant.pit import pit_coverage as C
from src.quant.pit import rich_panel as R
from src.quant.pit.rich_panel_catalog import CATALOG, COMMON

ROOT = Path(__file__).resolve().parents[2]
ASSURANCE = {
    "profitability": "HIGH: as-reported SEC vintages, acceptance-time gated",
    "value": "MEDIUM-HIGH: SEC vintages plus PIT shares x unadjusted close; share basis and split restatement add error",
    "investment": "HIGH: as-reported SEC vintages; year-ago balances from the vintages known then",
    "quality": "HIGH: as-reported SEC vintages",
    "leverage": "HIGH: as-reported SEC vintages (both debt legs required)",
    "growth": "HIGH: as-reported TTM now against the TTM computed at the year-ago filing",
    "capital_structure": "MEDIUM-HIGH: shares depend on the cover-page/balance-sheet basis and split table (2014+)",
    "event": "HIGH: filing acceptance times",
    "control": "GATED: withheld unless the security-master PIT gate passes",
}


def pct(value) -> str:
    return "-" if value is None or (isinstance(value, float) and pd.isna(value)) else f"{value:.1%}"


def render_security_master() -> str:
    m = json.loads((ROOT / "data/manifests/security_master_coverage_v3.json").read_text())
    ev, cov = m["evidence"], m["coverage"]
    lines = [
        "# PIT security master - status (`security-master-v3`)", "",
        "Generated by `python -m scripts.quant.render_pit_docs` from `data/manifests/security_master_coverage_v3.json`.", "",
        f"**`security_master_pit` = {str(m['security_master_pit']).lower()}** | `size_features_allowed` = {str(m['size_features_allowed']).lower()} | `neutralization_allowed` = {str(m['neutralization_allowed']).lower()}", "",
        "The flag is computed mechanically from thresholds written before coverage was measured (`src/quant/pit/pit_coverage.py::THRESHOLDS`):",
        "trusted identity >= 95% of universe name-dates in every year from 2015 and every validation fold; contradicted <= 2%; SIC >= 95% of identified;",
        "market-cap >= 90% of identified in every fold for size features. Nothing was relaxed after the numbers were seen.", "",
        "## Method", "",
        "* Identity is a **SEC CIK**. A ticker is a label worn for a **dated window taken from price data** (capped at the 2025-05-09 research cutoff);",
        "  windows split at gaps > 250 days so a re-used ticker is two windows.",
        "* The CIK comes from the SEC current ticker map, or - where absent - from *exact* normalised issuer-name evidence in dated filings (current name, `former`, and",
        "  the submissions API `formerNames`); ambiguous names are left unresolved. The current map never creates an effective date. OpenFIGI is not used.",
        "* Every link is then tested against the filings: `A_CONFIRMED`, `B_CONSISTENT` (trusted); `C_PARTIAL`, `X_CONTRADICTED`, `D_NO_PERIODIC_FILINGS`, `UNRESOLVED` (never used for features).",
        "* A holding-company succession is linked to its predecessor CIK only on exact issuer-name continuity with adjacent filing periods (`SUCCESSOR_NAME_CONTINUITY`).",
        "* Industry: SEC `sic` **as of each filing** (the SEC readme states this) as dated intervals, mapped to Fama-French 12/17/48 by the Kenneth French SIC files (hashes below). No GICS.",
        "* Shares: `dei:EntityCommonStockSharesOutstanding` from the SEC `companyconcept` API dated by the FSDS acceptance time of its accession, plus the balance-sheet count;",
        "  market cap = shares (split-adjusted after acceptance) x unadjusted close. Exits: Form 25 / 15 / 8-K items from SEC submissions; no delisting returns invented.", "",
        "## Evidence", "",
        f"Universe tickers (through 2025-05-09): {m['universe_symbols']}; links graded: {ev['links']}; resolved tickers (A or B): {ev['resolved_tickers']}; **unresolved tickers: {m['unresolved_tickers']}**.", "",
        "| Grade | Links |", "|---|---:|", *[f"| `{g}` | {n} |" for g, n in sorted(ev["grades"].items())], "",
        "| Method | Links |", "|---|---:|", *[f"| `{g}` | {n} |" for g, n in sorted(ev["methods"].items())], "",
        f"Ticker-reuse candidates (a ticker with more than one window): {m['ticker_reuse_candidates']}. Identity intervals: {m['identity_intervals']}; classification intervals: {m['classification_intervals']};",
        f"name intervals: {m['name_intervals']}; share vintages: {m['shares_vintages']:,} ({m['shares_by_basis']}); exit events: {m['exit_events']} ({m['exit_quality']}) over {m['closed_identities']} closed identities.", "",
        "## Coverage of the frozen research rows (universe name-dates)", "",
        "| Period | Rows | Trusted (A/B) | Contradicted | Partial | No 10-K/10-Q | Unresolved | SIC of identified | Shares of identified | Market cap of identified |", "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for key in ("by_year", "by_period"):
        for label, v in cov[key].items():
            lines.append(f"| {label} | {v['rows']:,} | {pct(v['identity_trusted'])} | {pct(v['identity_contradicted'])} | {pct(v['identity_partial'])} | {pct(v['no_periodic_filings'])} | {pct(v['unresolved'])} | {pct(v['sic_of_identified'])} | {pct(v['shares_of_identified'])} | {pct(v['market_cap_of_identified'])} |")
        lines.append("")
    lines += ["## Why the flag is false" if not m["security_master_pit"] else "## Gate", ""]
    lines += [f"* {f}" for f in m["failures"][:6]] + ([f"* ... {len(m['failures']) - 6} more" ] if len(m["failures"]) > 6 else [])
    lines += ["", "What the gap is, honestly: roughly a tenth of the universe by name-date are **foreign private issuers and funds that file 20-F/40-F/N-CSR, not 10-K/10-Q** (`D_NO_PERIODIC_FILINGS`);",
              "about six percent are **delisted names whose vendor name or CIK cannot be recovered** (`UNRESOLVED`, mostly absent from the vendor symbol table); about one percent are **genuine reuse or re-domiciliation** (`X_CONTRADICTED`).",
              "Closing it needs IFRS/20-F tag maps for the first group and vendor-independent delisted-name evidence for the second. Until then fundamentals are **missing, never zero**, for those names, and industry/size controls are withheld.", "",
              "## Source hashes", "", *[f"* French SIC {k}: `{v}`" for k, v in m["french_sic_sha256"].items()], ""]
    return "\n".join(lines)


def render_catalog(manifest: dict) -> str:
    cov = manifest["coverage"]
    lines = [
        "# PIT feature catalog (rich panel)", "",
        f"Dataset `{manifest['dataset_id']}` (`{manifest['panel_version']}`), {manifest['feature_count']} features = {manifest['baseline_feature_count']} unchanged baseline + {manifest['new_feature_count']} new. Generated from `src/quant/pit/rich_panel_catalog.py` and measured coverage.", "",
        "## Rules that apply to every new feature", "",
        f"* **Timestamp rule:** {COMMON['timestamp_rule']}.", f"* **Minimum lag:** {COMMON['minimum_lag']}.",
        f"* **Cross-sectional transform / winsorisation:** {COMMON['cross_sectional_transform']}.", f"* **Missing-value policy:** {COMMON['missing_policy']}.",
        "* **Source:** SEC Financial Statement Data Sets (`sec-core-facts-v3`) unless a column says otherwise; market cap uses the unadjusted close of the same date.", "",
        "## Baseline features (unchanged, identical values to `ds-491d761b9f2a6fc4`)", "",
        "`" + "`, `".join(R.BASELINE_FEATURES) + "`", "",
        "Price, liquidity, volatility, trend and market-regime features are PIT by construction (trailing windows only); the five rates features use the Treasury curve with a one-session lag (ALFRED vintages are `BLOCKED_EXTERNAL_FRED_KEY`).", ""]
    for family in ("profitability", "value", "investment", "quality", "leverage", "growth", "capital_structure", "event", "control"):
        names = [n for n in list(R.NEW_FEATURES) + list(R.CONTROL_FEATURES) if R.FAMILY.get(n) == family]
        if not names:
            continue
        lines += [f"## {family.replace('_', ' ').title()}", "", f"PIT assurance: {ASSURANCE[family]}.", "",
                  "| Feature | Formula | Inputs | First valid | Coverage | Known limitation |", "|---|---|---|---|---:|---|"]
        for name in names:
            col = f"{name}_xs"
            c = cov.get(col)
            first = c["first_valid_date"] if c else "withheld"
            share = pct(c["coverage"]) if c else "withheld"
            formula, inputs, limit = CATALOG[name]
            lines.append(f"| `{name}` | {formula} | {inputs} | {first} | {share} | {limit or '-'} |")
        lines.append("")
    return "\n".join(lines)


def render_audit(manifest: dict) -> str:
    m = json.loads((ROOT / "data/manifests/security_master_coverage_v3.json").read_text())
    tag = json.loads((ROOT / "data/manifests/sec_fact_coverage_v3.json").read_text())
    cov, exit_check = manifest["coverage"], manifest["missingness_vs_exit"]
    classification = pd.read_parquet(ROOT / "data/curated/security_master_v3/security_classification_interval.parquet")
    multi = classification.groupby("cik").size()
    panel = pd.read_parquet(ROOT / "data/research/derived/rich_pit_panel.parquet", columns=["date", "symbol", "security_id", "ff12", "sic", "filing_lag_days_xs"]) if False else None
    families = {}
    for name in manifest["new_features"]:
        base = name[:-3] if name.endswith("_xs") else name
        families.setdefault(R.FAMILY.get(base, "other"), []).append(cov[name]["coverage"])
    lines = [
        "# Rich PIT panel audit", "",
        f"Dataset `{manifest['dataset_id']}`: {manifest['rows']:,} universe name-dates, {manifest['securities']} securities ({manifest['symbols']} tickers), {manifest['date_min']} to {manifest['date_max']}, "
        f"{manifest['feature_count']} features (`{manifest['feature_hash'][:16]}...`), content hash `{manifest['content_hash'][:16]}...`. Holdout touched: **false**. Built from commit `{manifest['build_commit'][:10]}`.", "",
        "This document reports what the panel contains and does not contain. It contains no performance evidence: no feature was scored against any return.", "",
        "## Identity resolution and survivorship", "",
        f"* Trusted (A/B) identity by fold: " + ", ".join(f"{k} {pct(v['identity_trusted'])}" for k, v in m['coverage']['by_period'].items() if k.startswith('fold_')) + ".",
        f"* `security_master_pit` = **{str(m['security_master_pit']).lower()}**; size/industry controls **{'allowed' if manifest['controls_allowed'] else 'withheld'}**.",
        f"* Unresolved tickers: {m['unresolved_tickers']} (sample: {', '.join(m['unresolved_sample'][:20])}...). Foreign/no-10-K issuers (`D`): {m['evidence']['grades'].get('D_NO_PERIODIC_FILINGS', 0)} links.", "",
        "**Survivorship through missingness.** Fundamentals are absent for names the security master cannot resolve, and those are disproportionately delisted names. A model that sees only",
        "`NaN` could in principle learn 'missing = will delist'. Measured on the panel rows (names whose price series ends within 30 days versus all others):", "",
        f"| | Names exiting within 30 days | All other rows |", "|---|---:|---:|",
        f"| ROA feature present | {pct(exit_check['share_present_if_exiting_soon'])} | {pct(exit_check['share_present_otherwise'])} |",
        f"| Trusted identity | {pct(exit_check['share_identity_trusted_if_exiting_soon'])} | {pct(exit_check['share_identity_trusted_otherwise'])} |", "",
        f"({exit_check['rows_exiting_within_30_days']:,} rows are in the exiting group.) A gap between the columns is a leakage channel and is one reason EXP-011 reports a covered-subset ordering diagnostic and imputes missing values with training-fold medians rather than a flag.", "",
        "## Coverage by year and by fold (share of universe name-dates with a value)", "",
        "| Feature family | Mean coverage | Min feature | Max feature |", "|---|---:|---:|---:|",
        *[f"| {f} | {pct(sum(v) / len(v))} | {pct(min(v))} | {pct(max(v))} |" for f, v in sorted(families.items())], "",
        "Per-feature first-valid dates and coverage by year and period are in `data/manifests/rich_pit_panel_manifest.json` and `docs/PIT_FEATURE_CATALOG.md`.", "",
        "## SEC availability", "",
        f"* 58 quarterly archives verified (`docs/LOCAL_DATA_INVENTORY_FINAL.md`); {tag['coverage']['rows']:,} curated as-reported rows from {tag['coverage']['filings']:,} filings and {tag['coverage']['ciks']:,} CIKs.",
        f"* Availability is acceptance time in US Eastern, next session for filings at or after 16:00. Fallback and tag-disagreement rates per fact family: `docs/SEC_TAG_MAP_AUDIT.md`.",
        "* Restatements are preserved as vintages. Real-data truncation test (2019Q1-Q4 cut at 2019-07-01): 150,514 later vintages of facts first reported before the cut, 11,347 amendment rows after it, and every earlier row and both PIT views byte-identical.", "",
        "## Industry and size", "",
        f"* SIC as of each filing gives {len(classification):,} dated intervals over {classification['cik'].nunique()} CIKs; {(multi > 1).sum()} CIKs ({(multi > 1).mean():.1%}) change SIC at least once, which is what an as-of-filing field should show (a current-only field would show none).",
        "* Fama-French 12/17/48 come from the Kenneth French SIC files (hashes in `docs/PIT_SECURITY_MASTER_STATUS.md`). There are no GICS sectors anywhere.",
        f"* Market cap is present for {pct(m['coverage']['by_period']['fold_0']['market_cap_present'])}-{pct(m['coverage']['by_period']['fold_7']['market_cap_present'])} of name-dates by fold; it is the input to the value features, but the `log_market_cap` and industry-relative controls are {'included' if manifest['controls_allowed'] else 'withheld by the gate'}.", "",
        "## Limits that remain", "",
        "* 20-F/40-F filers have no fundamentals (IFRS mapping not built). Delisted names without a recoverable name have none either.",
        "* The universe is the frozen top-250-by-liquidity set; delisting bounds before 2017-10-26 are inferred (`docs/PIT_SECURITY_MASTER_PLAN.md`).",
        "* Shares use the cover-page count where the API supplies one and the balance-sheet count otherwise; multi-class companies sum classes in the cover count (flagged) and are excluded from the bulk balance-sheet count.",
        "* Splits are taken from a table that begins 2014-03-28. Market cap for a split before that date is not restated.",
        "* Cross-sectional ranks are formed among names with a value, so the peer group changes with coverage over time.", ""]
    return "\n".join(lines)


def main() -> int:
    (ROOT / "docs/PIT_SECURITY_MASTER_STATUS.md").write_text(render_security_master())
    manifest_path = ROOT / "data/manifests/rich_pit_panel_manifest.json"
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text())
        (ROOT / "docs/PIT_FEATURE_CATALOG.md").write_text(render_catalog(manifest))
        (ROOT / "docs/RICH_PIT_PANEL_AUDIT.md").write_text(render_audit(manifest))
    print("rendered docs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
